#!/bin/sh
# based on ccl/scripts/ccl64, which is too stupid to figure out where it is being run from or whether it is 32/64 bit
# sets -no-init flag

export CCL_DEFAULT_DIRECTORY=$PWD/ccl

if [ -z "$OPENMCL_KERNEL" ]; then
    case `uname -s` in
	Darwin)
	    case `arch` in
		i386)
		    OPENMCL_KERNEL=dx86cl ;;
		x86_64)
		    OPENMCL_KERNEL=dx86cl64 ;;
	    esac
	    ;;
	Linux)
	    case `uname -m` in
		x86_64)
		    OPENMCL_KERNEL=lx86cl64 ;;
		*86*)
		    OPENMCL_KERNEL=lx86cl ;;
		*)
		    echo "Can't determine machine architecture.  Fix this."
		    exit 1
		    ;;
	    esac ;;
	*)
	    echo "Can't determine host OS.  Fix this."
	    exit 1
	    ;;
    esac
fi

exec ${CCL_DEFAULT_DIRECTORY}/${OPENMCL_KERNEL} --no-init "$@"
